qemu-system-i386 -boot order=c -m 512 -monitor stdio -serial file:serial.log ^
-device ich9-intel-hda ^
-audiodev dsound,id=snd0 ^
-device hda-output,audiodev=snd0 ^
-audio dsound,model=sb16 ^
-audiodev dsound,id=pcspeaker -machine pcspk-audiodev=pcspeaker ^
-drive if=none,id=usbstick,format=raw,file=GreenwoodOS.img ^
-drive id=disk,file=GreenwoodOS.img,if=none,format=raw ^
-drive id=disk2,file=filesystem.iso,if=none,format=raw ^
-device ahci,id=ahci ^
-device ide-hd,drive=disk2,bus=ahci.0,bootindex=2 ^
-device ide-hd,drive=disk,bus=ahci.1,bootindex=1 ^
-device qemu-xhci ^
-device usb-mouse