qemu-system-i386 -s -boot order=c -m 2G -monitor stdio -serial file:serial.log -no-reboot -d int,cpu_reset \
-audiodev pipewire,id=Sound \
-drive id=disk,file=./GreenwoodOS.iso,if=none,format=raw \
-drive id=disk3,file=fstest.img,if=none,format=raw \
-drive id=disk2,file=filesystem.iso,if=none,format=raw \
-device ahci,id=ahci \
-device ide-hd,drive=disk3,bus=ahci.0,bootindex=2 \
-device ide-hd,drive=disk,bus=ahci.1,bootindex=1 \
-device ide-hd,drive=disk2,bus=ahci.2,bootindex=3 \
-audiodev pipewire,id=speaker -machine pcspk-audiodev=speaker \
-audio pipewire,model=ac97 \
-device qemu-xhci,id=xhci \
-rtc base=localtime,clock=host \
-enable-kvm \
-netdev user,id=mynet0,net=10.0.1.0/24,dhcpstart=10.0.1.10 \
-device rtl8139,netdev=mynet0 \
-object filter-dump,id=f1,netdev=mynet0,file=netdump.dat \
-smp sockets=1,cores=4,threads=1
