VAR LOADER "/A/drivers/loader.elf"
VAR ISOFS "/A/drivers/isofs/isofs.elf"
VAR BUFFS "/A/drivers/buffs/buffs.elf"
VAR LISPENG "/A/drivers/lispeng/lisp.elf"
#VAR SETBG "/A/utils/setbg_scale/setbg_scale.elf"
VAR SETBG "/A/utils/SetBG/setbg.elf"
VAR CLOCK "/A/utils/clock/clock.elf"
VAR TBAR "/A/utils/tbar/tbar.elf"
#VAR BG "/A/Pictures/bliss.tga"
VAR BG "/A/Pictures/skyline.tga"
EXEC CLOCK "-wb"
EXEC LOADER ISOFS "-w"
EXEC LOADER LISPENG
WEXEC LOADER BUFFS "-w"
EXEC TBAR "/A/OS/tbar.ini"
WEXEC SETBG BG
EXEC "/A/utils/term2/term2.elf"

