VAR SETBG "/A/utils/setbg_scale/setbg_scale.elf"
VAR CLOCK "/A/utils/clock/clock.elf"
VAR TBAR "/A/utils/tbar/tbar.elf"
VAR TERM "/A/utils/term2/term2.elf"
EXEC CLOCK "-wb"
EXEC TERM
EXEC TBAR "/A/OS/tbar.ini"
#EXEC "/A/utils/term2/term2.elf"
SETBG "/A/Pictures/skyline.tga"
