VAR SETBG "/A/utils/setbg_scale/setbg_scale.elf"
VAR CLOCK "/A/utils/clock/clock.elf"
VAR TBAR "/A/utils/tbar/tbar.elf"
VAR TERM "/A/utils/term2/term2.elf"
EXEC CLOCK "-wb"
#EXEC SETBG "/A/Pictures/vaporwave.tga"
#EXEC TERM "/A/lisp/lisp.elf" "-w"