VAR SETBG "/A/utils/setbg_scale/setbg_scale.elf"
VAR CLOCK "/A/utils/clock/clock.elf"
VAR TBAR "/A/utils/tbar2/tbar.elf"
VAR TERM "/A/utils/term2/term2.elf"
EXEC CLOCK
#EXEC TERM
#WEXEC SETBG "/A/AJB/gab.tga"
EXEC TBAR "/A/OS/tbar.ini"
EXEC "/A/utils/audioctrl/audioctrl.elf"

#EXEC TERM "/A/lisp/lisp.elf" "-w"