#ifndef _USR_SYSCALL_H
#define _USR_SYSCALL_H

#define SYSCALL_WINDOW_OPEN 0x01
#define SYSCALL_WINDOW_CLOSE 0x02
#define SYSCALL_WINDOW_COPY 0x03
#define SYSCALL_GETC 0x05
#define SYSCALL_EXEC 0x06
#define SYSCALL_SET_SCHEDULE 0x07
#define SYSCALL_CONSOLE_PRINT 0x08
#define SYSCALL_CONSOLE_OPEN 0x09
#define SYSCALL_CONSOLE_CLOSE 0x0A
#define SYSCALL_KMALLOC 0x0B
#define SYSCALL_CONSOLE_PRINTARGS 0x0C
#define SYSCALL_CHDIR 0x12
#define SYSCALL_GET_DIR 0x13
#define SYSCALL_GET_KERNEL_FEATS 0x17
#define SYSCALL_CREATDIR 0x1A
#define SYSCALL_SRAND 0x1D
#define SYSCALL_RAND 0x1E
#define SYSCALL_EXIT 0x1F
#define SYSCALL_MEM_REQ 0x20
#define SYSCALL_KBD_EVENT 0x21
#define SYSCALL_MEM_RSV 0x23
#define SYSCALL_START_TASK 0x26
#define SYSCALL_MEM_FREE 0x2B
#define SYSCALL_CONSOLE_OPEN_VP 0x2E
#define SYSCALL_VFS_LISTDIR 0x30
#define SYSCALL_TASK_LOCK 0x32
#define SYSCALL_YIELD 0x34
#define SYSCALL_OPEN 0x35
#define SYSCALL_CLOSE 0x36
#define SYSCALL_READ 0x37
#define SYSCALL_WRITE 0x38
#define SYSCALL_SEEK 0x39
#define SYSCALL_CREAT 0x3A
#define SYSCALL_DUPFD 0x3B
#define SYSCALL_FORK 0x3C
#define SYSCALL_TRUNCATE 0x3F
#define SYSCALL_WAIT 0x40

#endif